name: svetlana-radchenko-landing
static_sites:
- name: web
  github:
    repo: LevFaiger/svetlana-radchenko-landing
    branch: main
    deploy_on_push: true
  build_command: npm run build && ls -la out/
  output_dir: out
  index_document: index.html
  error_document: 404.html
  envs:
  - key: NODE_ENV
    value: production
  - key: NEXT_TELEMETRY_DISABLED
    value: "1"